pipeline {
    agent any

    environment {
        PYTHON = 'python3'
        GITHUB_CREDENTIALS = credentials('github-creds')
        DOCKER_HUB_CREDENTIALS = credentials('docker-hub-credentials')
        DOCKER_IMAGE = "odegichristine/messaging-app"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/OdegiChristine/alx-backend-python.git',
                    credentialsId: 'github-creds'
            }
        }

        stage('Setup Python') {
            steps {
               sh '''
                    python3 -m venv venv
                    source venv/bin/activate
                    pip install --upgrade pip
                    pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Install dependencies & Test') {
            steps {
                sh 'pip3 install -r messaging_app/requirements.txt'
                sh 'pytest --junitxml=report.xml'
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }


        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t $DOCKER_IMAGE:${env.BUILD_NUMBER} ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    sh "echo $DOCKER_HUB_CREDENTIALS_PSW | docker login -u $DOCKER_HUB_CREDENTIALS_USR --password-stdin"
                    sh "docker push $DOCKER_IMAGE:${env.BUILD_NUMBER}"
                }
            }
        }

        stage('Publish Report') {
            steps {
                junit 'test-results.xml'
            }
        }
    }

    triggers {
        // Pipeline will only run when triggered manually
    }
}
