name: Docker Build and Push

on:
  push:
    branches:
      - main   # Trigger only on pushes to main
  workflow_dispatch:  # Allow manual trigger

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/messaging-app:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/messaging-app:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/messaging-app:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/messaging-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/messaging-app:latest
